<?php

use Drupal\views_local_tasks\Plugin\Derivative\CustomViewsLocalTask;

/**
 * Implements hook_views_plugins_display_alter().
 */
function views_local_tasks_views_plugins_display_alter(array &$plugins) {
  $plugins["page"]["class"] = 'Drupal\views_local_tasks\Plugin\views\display\PageWithLocalTasks';
}

/**
 * Implements hook_local_tasks_alter().
 */
function views_local_tasks_local_tasks_alter(&$local_tasks) {
  $container = \Drupal::getContainer();
  $local_task = CustomViewsLocalTask::create($container, 'views_view');
  $local_task->alterLocalTasks($local_tasks);
}

/**
 * Implements hook_module_implements_alter().
 */
function views_local_tasks_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'local_tasks_alter' && isset($implementations['views_local_tasks'])) {
    // Move this module's implementation of the to the end of the list.
    $hookInit = $implementations['views_local_tasks'];
    unset($implementations['views_local_tasks']);
    $implementations['views_local_tasks'] = $hookInit;
  }
}

/**
 * Implements hook_config_schema_info_alter().
 */
function views_local_tasks_config_schema_info_alter(&$definitions) {
  $definitions['views.display.page']['mapping']['menu']['mapping']['as_local_task'] = [
    'type' => 'boolean',
    'label' => 'Local task only',
  ];

  $definitions['views.display.page']['mapping']['menu']['mapping']['local_task_link_title'] = [
    'type' => 'text',
    'label' => 'Local task link title',
  ];

  $definitions['views.display.page']['mapping']['menu']['mapping']['local_task_parent'] = [
    'type' => 'string',
    'label' => 'Local task parent',
  ];

  $definitions['views.display.page']['mapping']['menu']['mapping']['local_task_weight'] = [
    'type' => 'integer',
    'label' => 'Local task weight',
  ];
}
