<?php

/**
 * @file
 * Editoria11y module file.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Url;
use Drupal\taxonomy\TermInterface;
use Drupal\Core\Routing\RouteObjectInterface;

/**
 * Implements hook_page_attachments().
 *
 * Attaches Editoria11y library and config based on context.
 */
function editoria11y_page_attachments(array &$attachments) {

  $attachments['#cache']['contexts'][] = 'user.permissions';
  if (!\Drupal::currentUser()->hasPermission('view editoria11y checker')) {
    return;
  }

  $attachments['#cache']['contexts'][] = 'route';
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    if (substr($route_name, 0, 12) == 'editoria11y.') {
      $apiUrl = Url::fromRoute('editoria11y.api_report')->toString();
      $sessionUrl = Url::fromRoute('system.csrftoken')->toString();
      $attachments['#attached']['drupalSettings']['editoria11y']['api_url'] = $apiUrl;
      $attachments['#attached']['drupalSettings']['editoria11y']['session_url'] = $sessionUrl;
      $attachments['#attached']['library'][] = 'editoria11y/editoria11y-admin';
    }
    return;
  }

  // Determine which dismissals are permitted.
  // "Ignore" is a global toggle, "mark OK" is per-user.
  $attachments['#cache']['tags'][] = 'config:editoria11y.settings';
  $config = \Drupal::config('editoria11y.settings');

  // Confirm this is a "view" (not edit) route, and set last-changed time.
  $show = FALSE;
  // @todo convert to standard Bool call once schema is updated
  $sync = !$config->get('disable_sync');

  $attachments['#cache']['contexts'][] = 'url';
  $request = \Drupal::request();

  // Get languages.
  $attachments['#cache']['contexts'][] = 'languages';
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if ($language && $language !== 'en') {
    $attachments['#attached']['library'][] = 'editoria11y/editoria11y-localized';
  }
  else {
    $attachments['#attached']['library'][] = 'editoria11y/editoria11y';
  }

  // Build URI after filtering nonpreserved parameters
  // $page_path = $request->getPathInfo();
  $page_path = Url::fromRoute('<current>')->toString();
  if (!empty($config->get('preserve_params'))) {
    // Based on core "request->normalizeQueryString()"
    $query = $request->getQueryString();
    if ('' !== $query) {
      $parts = [];
      $order = [];
      $preserved_params = explode(',', $config->get('preserve_params') ?? '');
      foreach (explode('&', $query ?? '') as $param) {
        if ('' === $param || '=' === $param[0]) {
          // Ignore useless delimiters, e.g. "x=y&".
          // Also ignore pairs with empty key, even if there was a value, e.g.
          // "=value", as such nameless values cannot be retrieved anyway.
          // PHP also does not include them when building _GET.
          continue;
        }
        $keyValuePair = explode('=', $param, 2);

        if (in_array($keyValuePair[0], $preserved_params)) {
          // GET parameters, that are submitted from a HTML form, encode spaces
          // as "+" by default
          // (as defined in enctype application/x-www-form-urlencoded).
          // PHP also converts "+" to spaces when filling the global _GET or
          // when using the function parse_str. This is why we use urldecode and
          // then normalize to RFC 3986 with rawurlencode.
          $parts[] = isset($keyValuePair[1]) ? rawurlencode(urldecode($keyValuePair[0])) . '=' . rawurlencode(urldecode($keyValuePair[1])) : rawurlencode(urldecode($keyValuePair[0]));
          $order[] = urldecode($keyValuePair[0]);
        }
      }
      if (!empty($parts)) {
        array_multisort($order, SORT_ASC, $parts);
        $page_path .= "?" . implode('&', $parts);
      }
    }
  }
  $page_path = substr($page_path, 0, 1000);

  $attachments['#cache']['tags'][] = 'editoria11y:dismissals_' . preg_replace('/[^a-zA-Z0-9]/', '', $page_path);

  if ($sync) {
    // Null or false unless both sync and permission are true.
    $allow_ok = \Drupal::currentUser()->hasPermission('mark as ok in editoria11y');
  }
  // Hiding can work via localStorage.
  $allow_hide = \Drupal::currentUser()->hasPermission('mark as hidden in editoria11y');

  $view_reports = \Drupal::currentUser()->hasPermission('manage editoria11y results');

  // @todo media?
  $entity_type = FALSE;
  $changed = 0;
  if ($route_name == 'entity.node.canonical') {
    // We can expect nodes to have a $changed value for smart loading.
    $changed = $route_match->getParameter('node')->changed->value;
    $show = TRUE;
  }
  elseif (substr($route_name, 0, 5) == 'view.') {
    // Ignore PHPStorm str_starts_with suggestion; requires PHP 8
    // Polite mode for views.
    $show = TRUE;
    // @todo figure out how to get view and media nice names
    $route_chunk = explode('.', $route_name);
    $entity_type = ucfirst($route_chunk[0]) . ": " . ucfirst(str_replace("_", " ", $route_chunk[1]));
  }
  elseif (strrpos($route_name, 'canonical', -1)) {
    // Polite mode for custom entities.
    $show = TRUE;
  }
  elseif (strrpos($route_name, 'preview', -1)) {
    // We load previews in assertive mode AND disable sync.
    $changed = \Drupal::time()->getRequestTime();
    $show = TRUE;
    $sync = FALSE;
    $allow_ok = FALSE;
    $allow_hide = FALSE;
  }
  else {
    // We load revisions and everything else in polite mode AND disable sync.
    $show = TRUE;
    $sync = FALSE;
    $allow_ok = FALSE;
    $allow_hide = FALSE;
  }

  // @todo we could add config for additional route names to allow $show on.
  if ($show) {
    if ($sync) {
      // Only views and other such canonical routes.
      if ($route = $request->attributes->get(RouteObjectInterface::ROUTE_OBJECT)) {
        // We need the title if sync is enabled.
        $page_title = \Drupal::service('title_resolver')->getTitle($request, $route);
        // @todo this fails on user route?
        if (is_array($page_title)) {
          $page_title = \Drupal::service('renderer')->renderPlain($page_title);
        }
      }
      if (empty($page_title)) {
        $page_title = $route_name;
      }

      // Entity will be found in the route parameters.
      if (($route = $route_match->getRouteObject()) && ($parameters = $route->getOption('parameters'))) {
        // Determine if the current route represents an entity.
        foreach ($parameters as $name => $options) {
          if (isset($options['type']) && strpos($options['type'], 'entity:') === 0) {
            $entity = $route_match->getParameter($name);
            if ($entity instanceof ContentEntityInterface && $entity->hasLinkTemplate('canonical') && $entity->type && $entity->type->entity) {
              $entity_type = $entity->type->entity->label();
            }
          }
        }
      }

      if ($entity_type == FALSE) {
        // Bundleless entities.
        if ($route_match->getParameter('taxonomy_term') instanceof TermInterface) {
          $entity_type = "Taxonomy: " . $route_match->getParameter('taxonomy_term')->label();
        }
        else {
          $route_chunk = explode('.', $route_name);
          $entity_type = ucfirst($route_chunk[0]) . ": " . ucfirst(str_replace("_", " ", $route_chunk[1]));
        }
      }

      // Get all dismissals for this page. We want all of OK and some of ignore.
      $results = \Drupal::service('editoria11y.dismissals_on_page');
      $result = $results->getDismissals($page_path);
      $dismissals = [];
      foreach ($result as $record) {
        if ($record->dismissal_status === "ok") {
          $dismissals[$record->result_key][$record->element_id] = "ok";
        }
        elseif ($record->uid == \Drupal::currentUser()->id()) {
          $dismissals[$record->result_key][$record->element_id] = "hide";
        }
      }
      $attachments['#attached']['drupalSettings']['editoria11y']['page_title'] = $page_title;
      $attachments['#attached']['drupalSettings']['editoria11y']['allow_hide'] = $allow_hide;
      $attachments['#attached']['drupalSettings']['editoria11y']['allow_ok'] = $allow_ok;
      $attachments['#attached']['drupalSettings']['editoria11y']['view_reports'] = $view_reports;
      $attachments['#attached']['drupalSettings']['editoria11y']['dashboard_url'] = Url::fromRoute('editoria11y.reports_dashboard')->toString();
    }
    else {
      $dismissals = FALSE;
    }

    $apiUrl = Url::fromRoute('editoria11y.api_report')->toString();
    $sessionUrl = Url::fromRoute('system.csrftoken')->toString();
    $attachments['#attached']['drupalSettings']['editoria11y']['api_url'] = $apiUrl;
    $attachments['#attached']['drupalSettings']['editoria11y']['session_url'] = $sessionUrl;
    $attachments['#attached']['drupalSettings']['editoria11y']['lang'] = $language;
    $attachments['#attached']['drupalSettings']['editoria11y']['page_path'] = $page_path;
    $attachments['#attached']['drupalSettings']['editoria11y']['entity_type'] = $entity_type;
    $attachments['#attached']['drupalSettings']['editoria11y']['route_name'] = $route_name;
    $attachments['#attached']['drupalSettings']['editoria11y']['preserve_params'] = $config->get('preserve_params');
    $attachments['#attached']['drupalSettings']['editoria11y']['include_null_params'] = $config->get('include_null_params');
    $attachments['#attached']['drupalSettings']['editoria11y']['assertiveness'] = $config->get('assertiveness');
    $attachments['#attached']['drupalSettings']['editoria11y']['changed'] = $changed;
    $attachments['#attached']['drupalSettings']['editoria11y']['no_load'] = $config->get('no_load');
    $attachments['#attached']['drupalSettings']['editoria11y']['ignore_all_if_absent'] = $config->get('ignore_all_if_absent');
    $attachments['#attached']['drupalSettings']['editoria11y']['content_root'] = $config->get('content_root');
    $attachments['#attached']['drupalSettings']['editoria11y']['shadow_components'] = $config->get('shadow_components');
    $attachments['#attached']['drupalSettings']['editoria11y']['ignore_elements'] = $config->get('ignore_elements');
    $attachments['#attached']['drupalSettings']['editoria11y']['embedded_content_warning'] = $config->get('embedded_content_warning');
    $attachments['#attached']['drupalSettings']['editoria11y']['hidden_handlers'] = $config->get('hidden_handlers');
    $attachments['#attached']['drupalSettings']['editoria11y']['download_links'] = $config->get('download_links');
    $attachments['#attached']['drupalSettings']['editoria11y']['ignore_link_strings'] = $config->get('ignore_link_strings');
    $attachments['#attached']['drupalSettings']['editoria11y']['sync'] = $sync;
    $attachments['#attached']['drupalSettings']['editoria11y']['dismissals'] = $dismissals;
    $attachments['#attached']['drupalSettings']['editoria11y']['theme'] = $config->get('ed11y_theme');
  }

}
